### ISSUE TITLE
Request: Build commands - Compile problems (Windows)

### ISSUE THREAD

**Issue by MythodeaLoL** [javi11/usenet-drive#111]
Hello, could you add the build commands, step by step.

If possible, for **Windows**, which is what I'm using. Because I tried several ways and I don't know how to compile it.

In rclone simply `go build` would solve it, but I'm not getting it here, neither `go build`, nor with npm, or `make build`, no `.exe` binary is generated. @javi11

**Comment by javi11** [comment]
Never tryed build it for windows yet but make build should generate the exe. Do you get some error building it?

**Comment by javi11** [comment]
I see, there is no windows build for the library that  I ‘m using, rapidyenc. I will probably need to contribute there to add the windows build

**Comment by Aerya** [comment]
What not just use WSL?

**Comment by MythodeaLoL** [comment]
updating the information, I was able to compile through **vscode**, installing **MinGW64**
but I still haven't been able to get rclone to connect via **webdav**. I didn't get any logs in vscode.

**Comment by MythodeaLoL** [comment]
Build Commands:
`go mod tidy && cd ./web && npm i && npm run build && cd .. && mkdir bin && go build -a -v -x -ldflags="-X main.Version=improve-download-speed-5 -extldflags=-static" -tags "windows amd64" -o ./bin/ ./...`

or
`go mod tidy`
`cd ./web && npm i && npm run build && cd ..`
`mkdir bin`
`go build -a -v -x -ldflags="-X main.Version=improve-download-speed-5 -extldflags=-static" -tags "windows amd64" -o ./bin/ ./...`
change the `-X main.Version` to downloaded version.

after run build again, delete the exe in the bin folder.
