### ISSUE TITLE
Recycle Bin feature for deleted files (keep nzb in a trash folder)

### ISSUE THREAD

**Issue by MythodeaLoL** [javi11/usenet-drive#112]
a recycle bin, just like gdrive and rclone have a configuration to send deleted items to the recycle bin, there could be a configuration to send deleted files to a trash folder, that is, send the deleted nzbs there, store the name of the files in the db with a checksum, and if possible, provide another configuration, keep them in the trash for X days, default 30 days.

would prevent accidental deletion. to restore, you would just go to the folder configured in the config.yaml settings and copy the nzb back to wherever you want, in the db, when starting usenet-drive, if the file did not exist in the specified folder, it would delete the db entry because it was not having the file in the trash anymore, just to not store anything unnecessarily in the db

EDIT:
sorry, i see now a duplicate post
https://github.com/javi11/usenet-drive/issues/74

**Comment by javi11** [comment]
Yep is already present :P. thanks for the ideas anyway https://github.com/javi11/usenet-drive/issues/74
