### ISSUE TITLE
Download corrupted when downloading with UsenetDrive.

### ISSUE THREAD

**Issue by MythodeaLoL** [javi11/usenet-drive#115]
I did extensive testing, I'll try to summarize everything, it's quite simple actually.

Uploading with UsenetDrive is perfect. NZB is sent flawlessly to usenet.

The Download is corrupt, it comes with errors, downloading from different Usenet hosts, after the download is done through UsenetDrive, somehow it doesn't work correctly, missing fragments, in short, a mess of bytes in certain parts. I copied the files with RaiDrive and rclone, it gave the same problem. Download management seems inefficient, it doesn't download constantly and at certain times it stops.

The problem of failures occurs even when viewing files in streaming, with failures through the player, and after copying the file to your PC, as it also has failures. The failures don't always seem to be in the same file locations, so I think usenettdrive isn't managing the download very well.

In a way, this is a serious flaw, as it corrupts the downloaded file.

sample file.
![Captura de tela 2024-03-03 175205](https://github.com/javi11/usenet-drive/assets/7586648/db0bc4b8-efb2-4512-aa3f-bed7aaaf45c9)
on the left the original, on the right the one downloaded by usenetdrive, this is a very corrupted part that demonstrates what I'm talking about.

@javi11

**Comment by javi11** [comment]
Could you please share logs or if you are using a different provider for download and upload. Remember that if you are using different backbones there could be delays on propagation of the articles since there is no upload check so far for this tool as other uploaders as Nyuu has.

**Comment by MythodeaLoL** [comment]
sorry @javi11 I don't have any logs, as the article downloads are not failing, they are just failing.

I downloaded them outside of usenetdrive with different providers and they were normal. Sorry I can't help with any more useful information.

**Comment by MythodeaLoL** [comment]
this version seems to have corrected the corrupt downloading https://github.com/javi11/usenet-drive/tree/530450ace33335a793b3b7063ff3e91678677ef2 @javi11 

**Review**:
This version seems to have fixed the corrupted download, but it still has serious problems in download management, using an exorbitant, unusual download bandwidth, from ~40mbps to more than ~400mbps for example, the RAM still seems to be a little high , it worries me in the case of multiple files being processed at the same time.
despite using the network a lot, the file doesn't download any faster, and the writing speed is slow, in this part, the main version is more stable, in main the file downloads more consistently without many oscillations, but main has the corrupt download problem on windows. I haven't tested it on Linux.

Another point about the **improve-download-speed** version that I mentioned is that it is reporting some fragments as corrupt, there seems to be some error, and it marks them in the DB as corrupt, but they are not, and apparently after some time it downloads normally, I noticed it when opening a file with VLC and doing some seeks.

tested using this configs:
```
article_size_in_bytes: 750000
max_download_workers: 15
```
**File Size 1.48GB**

Version `main`, debug pprof:
[heap (7).zip](https://github.com/javi11/usenet-drive/files/14611372/heap.7.zip)

I forgot to get the debug version **improve-download-speed**. :/

**Comment by javi11** [comment]
thanks for the info :). I'm almost there but not yet fix it, It Is hard to find a balance between speed and readability :S

**Comment by MythodeaLoL** [comment]
Fixed on dev version. ([improve-download-speed](https://github.com/javi11/usenet-drive/tree/improve-download-speed))
