### ISSUE TITLE
Feature request: option to upload nzb's to an indexer of choice

### ISSUE THREAD

**Issue by nicpaesk** [javi11/usenet-drive#119]
Suppose I have a Newznab-based indexer with some friends who share copyright rights for these files. It would be great to have the option to upload all new NZB files to that indexer, so friends can mount these files too. 

If this is not possible, then maybe another way to share these files with others, in a way that they don't have to accept the whole drive? 

All the best!

**Comment by javi11** [comment]
Yo @nicpaesk you can already share your nzbs and anyone can download them using nzbget for instance, the only issue is that the tool do not encrypt the content with password it just offuscate it. If you use rclone to encrypt the content who download it should use rclone also and your password. I have plans in the future to add an encryption by password

**Comment by nicpaesk** [comment]
That's what I thought, thank you very much for the precision. So do you think it would be feasible someday to have both the encryption by password and the ability to mount the files in the drive? I apologize for not being savvy enough to understand it on my own.

**Comment by javi11** [comment]
Yep,, it will be done as part of this task https://github.com/javi11/usenet-drive/issues/61
