### ISSUE TITLE
Upload from VPN 

### ISSUE THREAD

**Issue by nicpaesk** [javi11/usenet-drive#120]
I wonder how can I separate the download and upload network. I'd like to download using the normal connection, however since i'll be using burner accounts for upload, I would also like to use them through vpn. Is this currently possible?

The other way to make it work would be using two docker containers, with one of them connected to a gluetun container?

**Comment by javi11** [comment]
Right now vpn by itself is not part of the tool, if you want to use it you should connect through gluten. You can probably have two instances as you said, one for download one for upload and then merge it in rclone, and put one for readonly an the other for write only
