### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by appleszz** [javi11/usenet-drive#130]
hey hey hey!

I'm using go 1.22.2, trying to compile usenet-drive on Linux.  When I run `make` in the base directory several things churn along nicely until I hit the error pasted below.  Any hints?  Thanks!

Running: go mod tidy
Running: golangci-lint --timeout=5m
web/web.go:10:13: pattern all:dist: no matching files found (typecheck)
	//go:embed all:dist
	           ^
make: *** [makefile:41: golangci-lint] Error 1

**Comment by javi11** [comment]
Hi, you need first to build the admin panel

cd web && npm i && npm run build

**Comment by appleszz** [comment]
got it working now, thanks!

**Comment by javi11** [comment]
I will also release the binaries today for all major platforms ;)
