### ISSUE TITLE
The program stops responding when trying to read an nzb with 0 bytes.

### ISSUE THREAD

**Issue by MythodeaLoL** [javi11/usenet-drive#132]
For some reasons, when trying to synchronize some files, my HD ran out of space, causing a stop in the upload/download and a failure in rclone/usenet-drive, this seems to have led to the creation of an nzb with 0 bytes.

I understand that these problems can happen, but in this case, could there be a way to prevent a nzb file (with 0 bytes) from being created under these conditions?

### The real problem is, usenet-drive stops working correctly when trying to read this nzb with 0 bytes, it doesn't delete or overwrite it with an updated nzb, the program simply doesn't do anything anymore and the mounted folder gets stuck, stopping working.

**Comment by javi11** [comment]
m strange, if the file is not parseable it should marked as corrupted only, but let me verify

**Comment by javi11** [comment]
I fixed the issue on the last version, for the upload part I will rewrite how upload works, so it will be done as part of #68
