### ISSUE TITLE
Mysterious problem with same names and different extensions (video.mkv and video.srt/video.txt...)

### ISSUE THREAD

**Issue by MythodeaLoL** [javi11/usenet-drive#139]
It seems that when copying a .mkv file and .srt file or .txt file some problem happens.

When using rclone sync to synchronize cloud files with usenetdrive files, rclone sync is in a bit of a loop, copying these files.

I use filters to upload via usenetdrive only mkv files, the srt or txt files are saved together with the nzb files and should be mounted on the rclone virtual disk, but this doesn't seem to be happening.

This is causing a sync failure, where some srt/txt that contain the same name as the mkv are copied, but the mkv is not.

In other words, even with the filter to avoid nzbs with identical names because the nzb is not saved with the file extension, this mysterious problem still occurs.

<hr></hr>

### To summarize with another example.

I have usenetdrive mounted with rclone mount, I have a folder with `video.mkv` files, if I copy `video.srt` to the same folder mounted on usenetdrive, the `video.mkv` file disappears. without any apparent errors.

This is a serious flaw. 😭 

<hr></hr>
Using usenet-drive filters:

```
file_allow_list:
      - .mkv
      - .mp4
      - .avi
      - .ts
```

@javi11

**Comment by javi11** [comment]
I will check, but I have same scenario and this is not happening to me. Let me do some tests

**Comment by MythodeaLoL** [comment]
Isn't it better to use video.mkv.nzb? to avoid problems with the same file names but different extensions

**Comment by javi11** [comment]
Internally you have video.mkv.nzb that is mapped to video.mkv when mounted. So at the end they have different format

**Comment by MythodeaLoL** [comment]
here it is being saved as `video.nzb`, it is not saving with the `.mkv.nzb` extension
![image](https://github.com/javi11/usenet-drive/assets/7586648/47aa0fb0-d017-4930-bcf2-079f617c50fc)

![image](https://github.com/javi11/usenet-drive/assets/7586648/9f3403c9-34fd-48db-99f0-ba9eee87b6dc)

**Comment by javi11** [comment]
M true story it is a bug, As I don't upload other files only the video I don't fase the same issue

**Comment by x4ndo** [comment]
I'm also having the same problem, it would be nice if the nzb file was like file_name.mkv.nzb to support the same names with different extensions

for example:
file_name.mkv.nzb
file_name.rar.nzb
file_name.srt.nzb

**Comment by javi11** [comment]
It is a bug for sure ;). I will fix it, thanks :)
