### ISSUE TITLE
please explain more for the noobs like me

### ISSUE THREAD

**Issue by j0hnckuy** [javi11/usenet-drive#141]
I am on Win 11 and using the .exe binary to run this. I am also running rclone to host it as filesystem. I have also setup config with download / upload usenet server details.

I have mde a ./nzbs folder and made config.yaml to look at it. When I place files in this folder I don't see them rightaway in the mounted rclone drive. instead I need to restart for the files to be visible.

What is happenning in the background? Is it when I put files like .mkv, .mp3 in the ./nzbs folder are they getting uploaded to the usenet and eventually be seen in the mounted drive? When I delete the files from ./nzbs folder in the next run I see files are not there in the mounted drive as well. I am really confused how this works.

Can someone please explain this to me in the lamest language possible.

**Comment by javi11** [comment]
Hi,in order to work with the tool you always need to mount as a drive with rclone, then to upload/download you always need to move the files to the mounted folder after that, your files will be uploaded to Usenet. Summarizing you can not add anything directly to the nzbs folder

**Comment by j0hnckuy** [comment]
Thanks I'm understanding it now little by little. I now wants to shift the db to another computer, do I need to move .db file and .nzbs that were created by the program? If yes, will files/folder redownload via nzb to re-appear as in file system?
