### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by j0hnckuy** [javi11/usenet-drive#145]
I am trying to run this on a linux server in shell with very limited permissions. The error I'm getting is 

`Segmentation fault`

Just trying to confirm here that it's not due to the program itslef but because I'm not a sudo user on my server? I've contacted the admins regarding it too.

System info:

`Linux 4.4.249-1.el7.elrepo.x86_64 #1 SMP Mon Dec 28 13:05:51 EST 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by javi11** [comment]
You only get Segmentation fault??? the program doesn't need any kind of sudo permissions it just needs permissions of writing on the configured folders

**Comment by j0hnckuy** [comment]
Yes.

I am running 

` ./usenetdrive -c ./config/config.yaml`

I just get 'Segmentation fault'.

My config looks like this

> root_path: ./nzbs
> webdav_port: 8080
> api_port: 8081
> db_path: ./config/usenet-drive.db

and I'm running AMD64 version of the executable.

**Comment by javi11** [comment]
I found this https://groups.google.com/g/golang-nuts/c/KLu2ZXENXos apparently the problem is when you transfer the binary to your server

**Comment by j0hnckuy** [comment]
You're genius and many thanks although this was not related to the actual program issue but you went out of the way to help. Really appreciate it man. 

For future wanderers: I changed the transfer type to BINARY in filezilla.
