### ISSUE TITLE
db limitations

### ISSUE THREAD

**Issue by j0hnckuy** [javi11/usenet-drive#159]
Don't know what the problem is.

> /usenet-drive/usenetdrive -c /usenet-drive/config/config.yaml
> {"time":"2024-05-18T12:00:48.212534083+02:00","level":"INFO","msg":"Starting Usenet Drive 0.0.93"}
> {"time":"2024-05-18T12:00:48.212807359+02:00","level":"INFO","msg":"Config parameters:","config":{"LogPath":"/config/activity.log","RootPath":"/usenet-drive/nzbs","WebDavPort":"8080","ApiPort":"8081","Usenet":{"Download":{"MaxDownloadWorkers":15,"MaxRetries":8,"Providers":[{"Host":"..........","Port":119,"Username":".........","TLS":false,"MaxConnections":20,"InsecureSSL":false,"Id":""}]},> "Upload":{"DryRun":false,"FileAllowlist":[".mkv"],"MaxRetries":8,"Groups":["alt.binaries.test"],"Providers":> > [{"Host":"...............","Port":119,"Username":"...............","TLS":false,"MaxConnections":20,"InsecureSSL":false, Id":""}]},"FakeConnections":false,"ArticleSizeInBytes":1048576,"MaxConnectionIdleTimeInMinutes":30,"MaxConnectionTTLInMinutes":> 60},"DBPath":"/usenet-drive/config/usenet-drive.db","Rclone":{"VFSUrl":""},"Debug":false}}
> 2024/05/18 12:00:48 goose: no migrations to run. current version: 20231009091832
> {"time":"2024-05-18T12:00:48.214000807+02:00","level":"INFO","msg":"WebDav server started at http://localhost:8080"}
> {"time":"2024-05-18T12:00:48.214072558+02:00","level":"INFO","msg":"Api controller started at http://localhost:8081"}

rclone

> rclone mount --allow-other --async-read=true --dir-cache-time=1000h --buffer-size=32M --poll-interval=15s --rc --rc-no-auth --rc-addr=localhost:5572 --use-mmap --vfs-read-ahead=128M --vfs-read-chunk-size=32M --vfs-read-chunk-size-limit=2G --vfs-cache-max-age=504h --vfs-cache-mode=full --vfs-cache-poll-interval=30s --vfs-cache-max-size=50G --timeout=10m usenet: /root/meikey/  --umask=002 --allow-non-empty --verbose
> 2024/05/18 12:10:16 NOTICE: Serving remote control on http://127.0.0.1:5572/
> 2024/05/18 12:10:16 INFO  : webdav root '': poll-interval is not supported by this remote
> 2024/05/18 12:10:18 INFO  : vfs cache: cleaned: objects 1015 (was 1015) in use 0, to upload 0, uploading 0, total size 49.937G (was 49.937G)
> 2024/05/18 12:10:35 ERROR : webdav root '': Statfs failed: about call failed: Not Found: 404 Not Found

Also upon last run before it ceased to, I saw NZBs from Monday only. Somehow db deleted all the NZBs uploaded between Tuesday & today. Do I need to tweak something so that nzbs stays in db for custom amount of time?

EDIT: It's working now but the DB's got reset to 5-days ago. Do you have suggestions on saving db once a while? Also if I have DB and .nzbs can I fuse them on any other system? I should have backed up DB. I don't know what caused NZB deletion.

**Comment by javi11** [comment]
The nzbs are not saved to the dB, the db is only to save the corrupted nzbs by the moment and the program won't delete any of your files automatically it must be some external thing that you might have. To your second question, yes, you can copy and paste the nzbs folder and run it anywhere and you will end up with the same folder structure.
Hope that helps ;)

**Comment by j0hnckuy** [comment]
Thanks, I'll have to be more careful next time.

But it has happened twice. So was thinking.
