### ISSUE TITLE
stalled upload

### ISSUE THREAD

**Issue by j0hnckuy** [javi11/usenet-drive#161]
A file is visible in the fuse system/drive but it's counterpart nzb file isnt visible in the /nzbs dir. Is there a manual way to upload stalled file that for some reason wasnt uploaded? Or do I need to restart the program once in a while to scan and upload stalled files? the api at `http://localhost:8081/api/v1/` says nothing.

A quick note: my usenet upload server allows 50 connection and I've set it to use a mac of `20` `max_connection` at a time. I am uploading 2-5 files at a time. Do you think it's causing issue and that I need to lower down connections? My upload speed is slow.

**Comment by javi11** [comment]
Also your file extension must be allowed in the config in order to perform the upload

**Comment by j0hnckuy** [comment]
> Also your file extension must be allowed in the config in order to perform the upload

Yes, extension is allowed in the config file. Infact I see other files' nzbs with the same extension. I'll do the `refresh` as recommended by @MythodeaLoL

**Comment by j0hnckuy** [comment]
@MythodeaLoL running `rclone vfs/refresh recursive=true --rc --rc-addr=localhost:5572` is signalling error. 

> Error: unknown command "vfs/refresh" for "rclone"
> Run 'rclone --help' for usage.
> Fatal error: unknown command "vfs/refresh" for "rclone"

**Comment by j0hnckuy** [comment]
Done. But i think it's just running without printing anything. Is it normal?

**Comment by j0hnckuy** [comment]
@javi11 yes sir. I see uploading file_names.. I have kept log of all but I think these files I'm talking about couldn't go well for some reason. This had happened last time also when I asked any way to keep a backup copy of nzbs folder. All that time I was thinking I lost nzbs when in first place the nzbs were created ever for those files stored in webdav disk.

> I think is not recommended

I have created a cronjob to test it. Does forget/refresh every hour. Lets see how it goes.

In my experience, it has happened thrice with me and each time the program was open for more than 72 hours. I am thinking it as cache based issue or something purely by rclone and not U-D. Please throw some lights.

**Comment by javi11** [comment]
M i think I will need that error log, it can be caused by multiple facts, some network error or some other thing. Strange is that rclone should have a retry mechanism in those cases

**Comment by j0hnckuy** [comment]
Update : So far vfs/refresh is doing the job fine. I've set it to run once daily. I see match of file numbers with nzbs created. So far it seems to be working.

**Comment by j0hnckuy** [comment]
Will close this now. I'm monitoring rclone stdout if I see error I'll reopen this with error logs.
