### ISSUE TITLE
API

### ISSUE THREAD

**Issue by j0hnckuy** [javi11/usenet-drive#170]
I have a folder I'd like to manually upload it, cause it seems auto-upload function missed it. How do I access API endpoints? When I goto `http://localhost:8081/api/v1/` it gets errored out, It says `Not Found` in the web browser also `[api.yaml](https://github.com/javi11/usenet-drive/blob/main/internal/api/api.go).` file in the code DIR is missing or something - can't access it.

**Comment by javi11** [comment]
you can not perform an upload as an API, this is a webdav system, the only way to perform an upload is to move the file to the mount

**Comment by j0hnckuy** [comment]
i see,  okay.

thank you for answering.
