### ISSUE TITLE
How to create nzb files?

### ISSUE THREAD

**Issue by zozidalom** [javi11/usenet-drive#80]
Hi, I am running this tool in docker, I tried to use my nzb files, when I noticed that:

**This is not a tool to mount any nzb files, nzb files that are supported on the tool needs to be created by this tool.**

However I did not find anything in the documentation related to creating nzb files? How can I create one?

Thank you in advance for your assistance!

@javi11

**Comment by javi11** [comment]
Hi @zozidalom, to create nzb files with the tool you will need to run the tool, mount as a drive with (rclone) for instance and upload your files, like drag and drop. The program will automatically upload the file to usenet and create the nzb for you.

If you have a file already uploaded you can create one nzb manually following this format:

`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
  <head>
    <meta type="chunk_size">750000</meta>
    <meta type="file_size">3081486495</meta>
    <meta type="mod_time">2024-01-25 09:16:19</meta>
    <meta type="file_extension">.bin</meta>
    <meta type="file_name">big1.mkv.bin</meta>
  </head>
  <file poster="alt.binaries.test" date="1706170580873" subject="[1/1] - &#34;918f1eed-7097-48b7-8834-1f0d2347f540&#34; yEnc (1/4109)">
    <groups>
      <group>alt.binaries.test</group>
    </groups>
    <segments>
      <segment bytes="750000" number="1">8151e616-7f6d-40d4-84a8-278ee5a2859b@UsenetDrive</segment>
		....
    </segments>
  </file>
</nzb>
`

The file can not be compressed and each segment has to have the same size.

I will need to improve the documentation :P

**Comment by gyurix** [comment]
Hi @javi11 
I am working on this together with @zozidalom and for some reason the files are not getting uploaded to Usenet for some reason, I see the Uploading file message:
usenet-drive_1  | {"time":"2024-01-27T12:37:34.810607072Z","level":"INFO","msg":"Uploading file","name":"/nzbs/test.txt","size":4}
usenet-drive_1  | {"time":"2024-01-27T12:37:35.936400264Z","level":"INFO","msg":"Uploading file","name":"/nzbs/myvideo.mkv","size":5656654}
 but nothing happens after. I tested Usenet file uploads with nyuu before, and I had no issues that way.

**Comment by zozidalom** [comment]
Also in the web panel the upload and download speeds were not showing. But we saw 1 -> 3 increase in the open connections when we tried to upload 2 files.

**Comment by javi11** [comment]
Hey @gyurix, after you saw that message, you should see the message of File Uploaded successfully in some minutes depending on file size. The admin pannel should also show d/u speeds but is still not 100% accurate I need to improve it.

Are you using rclone with vfs cache to mount the webdav server?

**Comment by gyurix** [comment]
I figured out the issue. The default config was incorrect the ssl: key needs to be replaced to tls: 
After the changes the uploading works flawlessly. The speed still does not show up in the admin UI tho, but I verified that it completely maxed out my network speed, so it's pretty damn good.

**Comment by javi11** [comment]
Nice ;). I really need to improve the UI and the docs ajaj. I'm also working on using the same engine that nyuu is using to upload/download
