### ISSUE TITLE
Segments stop downloading after a while

### ISSUE THREAD

**Issue by javi11** [javi11/usenet-drive#87]
When a file is opened and segments are downloaded when close the file and wait some hours, the webdav server stops responding and no download happens anymore until service is restarted

**Comment by gyurix** [comment]
This error also happens with uploading and listing files in a folder.

**Comment by javi11** [comment]
Yep, I'm checking what is the issue :(. The problem with v0.0.78 is that it has a little memory leak, memory will grow bit by bit and will not decrease :(

**Comment by javi11** [comment]
Fixed on #94
