### ISSUE TITLE
[FEATURE] Add support for max_connections: 0 config option to temporarily disable using a provider

### ISSUE THREAD

**Issue by gyurix** [javi11/usenet-drive#92]
This is very easy to implement and will make life much easier, because currently if you want to do this, you need to comment out 12 config lines to disable a provider, this will change it to only be 2 line changes.

**Comment by javi11** [comment]
@gyurix You can already set a provider with max connections 0 to disable it

<img width="496" alt="Captura de pantalla 2024-02-06 a las 11 28 40" src="https://github.com/javi11/usenet-drive/assets/3855051/a4a682c5-3e24-4018-8d86-6d5af036dc26">
