### ISSUE TITLE
WEBDav server directory listing is extremely slow & is unneccessarily downloading data

### ISSUE THREAD

**Issue by gyurix** [javi11/usenet-drive#99]
For some reason if I open a directory the program starts generating massive network traffic & takes forever to show the list of files in the directory. I feel like it's trying to download the files somehow instead of just listing them, which is a terrible behavior and should not be happening. Please make it so it will only read any data from the usenet when I want to open a file, not when I want to list the files in a directory.

**Comment by javi11** [comment]
I will check, but the program will only downloads from usenet if the file is opened and reader. As far as I know, I think rclone fetch some data from files to cache some info when you open a file. Also, do you use rclone vfs cache, --async-read=true  and --dir-cache-time  ?

**Comment by gyurix** [comment]
Yes, I did try with the flags you have in README, I also tried connecting to the WebDAV using WinSCP instead of rclone and every single time I got the same results, which was that the directory opening time heavily relies on the number and size of files in that directory. It's a few seconds with 10x 50-150MB files and it's multiple minutes if you have over 50x 1GB sized files in it.

**Comment by javi11** [comment]
@gyurix The last nightly release should improve the directory load. So since we use rclone crypt is inevitable that it downloads the first segment of all the directories files to decode the file

**Comment by javi11** [comment]
@gyurix are you saving the nzb in HDD or in SDD or nvme? For the moment is highly recommended to use SDD or nvme disk to save the nzb since when a directory is opened the nzb of each file is opened to get the metadata. This will change in the future where the metadata will be fetched from a local database

**Comment by gyurix** [comment]
I get your point, but that's not the issue I am having. The issue is that when I open a directory, even with another WebDAV client, not just rclone instead of the program just reading the metadata from the head section of the nzb, it starts to download files. I checked the last nightly build, and it also has this exact same issue. Listing files in directories should work in a way, so they would not even require a usenet connection, since you only need to read the head section of the nzb files to fullfill such requests, nothing else.

**Comment by javi11** [comment]
It's what it does, on listing files, it will only fetch from the file the metadata block and the file tag nothing else. It just start downloading the files if where you use to mounted is asking for file Reads, that is what rclone actually does to try to fill the cache.

**Comment by gyurix** [comment]
2024/02/12 09:45:06 DEBUG : /: Opendir:
2024/02/12 09:45:06 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2024/02/12 09:45:09 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:        10.0s

2024/02/12 09:45:19 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:        20.0s

This happens when I open the directory according to the rclone logs, while my network usage goes up to max download speed. The same behavior happens when I open a directory while connecting to the WebDAV using WinSCP. So it has nothing to do with Rclone, and it's clearly doing something different than the intended behavior. Can you please double check what's going on?

**Comment by javi11** [comment]
@gyurix I did a little investigation and I found the following:

- When you list directories using the terminal there are no reads performed to the files so, it's fast.
- When you list directories using the explorer Windows/Max/Linux the explorer performs file reads to get some metadata from the file
- No matter if you use Rclone or another one like WinSCP, I tested it with the built-in mac webdav client, and the results are the same.

With that said, the only thing I can improve is, the startup of the download ;)

**Comment by gyurix** [comment]
Tested with terminal, both dir and cd commands triggers this bug. Currently if I want to download multiple files, then I need to code a separate software to find the exact filenames I can download based on the NZB files folder structure & filenames and trigger rclone copy on them 1 by 1. Otherwise things just don't work properly. And I need 2 rclone commands, 1 for the download the 2nd one for the decryption, because if I want to decrypt while downloading, that also gets buggy sometimes and only succeeds after multiple attempts. And even for making that work I needed to downgrade to version 0.0.84, because you broke something in the latest versions yet again.

You made a pretty awesome tool overall, but in it's current state it is absolutely not suitable to be mounted at all while this bug is present in it.

**Comment by javi11** [comment]
I will play around and see what can be done jejje. I'm not very experienced on Usenet connections yet :9.

**Comment by MythodeaLoL** [comment]
@gyurix try using `--network-mode` in **rclone**, this **disables** the preview of **thumbnails** which requires part of the file to be downloaded, if you have a lot of media files, this causes a lot of network usage.

**Comment by javi11** [comment]
@gyurix in the last nightly release I just merged a significant improvement on download/dir listing, I'm just performing a couple of test. Could you check whenever you have time to see if improves the perf on your case? 

I was using the following config

`
root_path: /nzbs
tmp_path: /tmp-files
db_path: /config/usenet-drive.db
debug: true
rclone:
  vfs_url: http://host.docker.internal:5573
usenet:
  download:
    max_download_workers: 15
    providers:
      - host: xx
        port: 80
        username: xx
        password: xx
        tls: true
        max_connections: 40
`

**Comment by MythodeaLoL** [comment]
for windows build:
Version `nightly `(today) - copy file is on 355kb, slow. streaming too, long time to open the video.
Version `main `- copy file  is 2MB+, working good. streaming is working good too.

Same versions using `max_download_workers: 1`, yes, only 1, but on `main` version is working fast.

**Comment by gyurix** [comment]
Thanks for the comment @MythodeaLoL please address that issue first @javi11 after that I will test.

**Comment by MythodeaLoL** [comment]
`max_download_workers` doesn't seem to be working very well, reducing the `max_buffer_size_in_mb` to `1`, seems to have helped when only 1 file is processed, trying to process 3 files, exhausts the download connections 50/50+2(52 connections), the ram goes to more of 10GB(RAM) to the point of almost crashing the computer if you don't close the usenet-drive. and the transfer speed doesn't seem to happen.

I don't know what other tests I can do to help identify the problem. If I have any more news, I'll edit it here.

**Comment by javi11** [comment]
Mm not sure how the program behaves with max_buffer_size_in_mb to 1mb but it shouldn't get all the ram. I have set up max_buffer_size_in_mb to 1024 so that will be the max mb it will take for the cache. Could you post some logs? Also this file http://localhost:8081/debug/pprof/heap

**Comment by MythodeaLoL** [comment]
Here @javi11 

```
2024/03/09 19:00:42 Allocated new queue in 57.7908ms; Capacity: 62914560
{"time":"2024-03-09T19:00:44.819341-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.8356963-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.8356963-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.8814119-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.9473223-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.9561772-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.9561772-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.9754655-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.9754655-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.9911682-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:00:44.9911682-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
2024/03/09 19:00:47 Allocated new queue in 140.0073ms; Capacity: 125829120
2024/03/09 19:00:48 Allocated new queue in 26.6382ms; Capacity: 62914560
2024/03/09 19:00:52 Allocated new queue in 150.1471ms; Capacity: 125829120
{"time":"2024-03-09T19:00:55.3677181-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
2024/03/09 19:00:57 Allocated new queue in 284.5935ms; Capacity: 251658240
2024/03/09 19:01:07 Allocated new queue in 231.673ms; Capacity: 251658240
{"time":"2024-03-09T19:01:17.7185581-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:17.7227512-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:17.7227512-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
2024/03/09 19:01:19 Allocated new queue in 769.8607ms; Capacity: 503316480
{"time":"2024-03-09T19:01:20.248099-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:20.248099-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:23.968539-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:23.968539-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:24.6701611-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:24.6701611-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:24.6745524-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
2024/03/09 19:01:25 Allocated new queue in 224.9032ms; Capacity: 503316480
{"time":"2024-03-09T19:01:31.6554709-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:31.7857327-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-09T19:01:31.8036415-03:00","level":"DEBUG","msg":"connecting to REDACTED-host2:119"}
2024/03/09 19:01:54 Allocated new queue in 249.4172ms; Capacity: 1006632960
2024/03/09 19:01:58 Allocated new queue in 346.3179ms; Capacity: 1006632960
2024/03/09 19:02:56 Allocated new queue in 479.8652ms; Capacity: 2013265920
2024/03/09 19:03:04 Allocated new queue in 1.5485176s; Capacity: 2013265920
{"time":"2024-03-09T19:04:01.0154865-03:00","level":"DEBUG","msg":"connecting to REDACTED-host2:119"}
2024/03/09 19:05:18 Allocated new queue in 8.0753603s; Capacity: 4026531840
2024/03/09 19:05:41 Allocated new queue in 21.9776128s; Capacity: 4026531840
```
[heap (4).zip](https://github.com/javi11/usenet-drive/files/14547959/heap.4.zip)

config.yaml
```
usenet:
  article_size_in_bytes: 3145728
  download:
    max_download_workers: 1
    max_buffer_size_in_mb: 1
    max_retries: 8
    providers:
      - host: "redacted"
        port: 443
        username: "redacted"
        password: "redacted"
        tls: true
        max_connections: 50

      - host: "redacted-host2"
        port: 119
        username: "redacted"
        password: "redacted"
        tls: false
        max_connections: 50
```

**Comment by MythodeaLoL** [comment]
I tested it again, I got some better results, but I still don't have an opinion yet, could I also test @gyurix ?

@javi11 the logs for #117 
[heap (5).zip](https://github.com/javi11/usenet-drive/files/14551576/heap.5.zip)
It seems like the RAM is fluctuating a lot.

**Comment by javi11** [comment]
@MythodeaLoL I just pushed another code that I'm currently testing to check if memory is estable. I also add a check for max_buffer_size_in_mb which should be at least the doble of the article_size_in_bytes.

**Comment by javi11** [comment]
Directory listing should be improved already in the last main version but in any case let´s continue here https://github.com/javi11/usenet-drive/issues/121 if some issue appears
